### ISSUE TITLE
Dropdown always requires controldness in react, which is different to other input elements

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1560] opened 2019-12-16 13:28 UTC
To reproduce, please checkout this commit: https://github.com/axa-ch/pod-baugarantie/commit/ce5e3f632b4905c5139beefb4cabb35c39855080

run `npm i && npm start` and then open following url:  http://0.0.0.0:8080/#/new

Then do the following:

Use dropdown "Land *" and select Lichtenstein. Then write something in any input field and it resets dropdown

If you first write in something in any input field and then use dropdown instead it wont let you use it. This is part of the with-react refactoring.

version 4.0.1

IS: Controldness in React is a must ONLY for Dropdown, also after re-rendering
SHOULD: Controldness is optional for all, including Dropdown, also after re-rendering

**Comment by markus-walther** [comment] 2020-01-06 16:53
The problem is that - contrary to the claims in this issue - the axa-dropdown component is driven *uncontrolled*.

This is because axa-ch/pod-baugarantie@ce5e3f6 is *before* the commit that introduces proper controlledness, by mentioning `value` as an axa-dropdown property.

If we checkout the latest axa-ch/pod-baugarantie instead, the erroneous behaviour described above goes away (i.e. in the example the selection 'Liechtenstein' is preserved).

**Comment by markus-walther** [comment] 2020-01-07 12:27
@LucaMele raised the interesting question why the *uncontrolled* driving of axa-dropdown seemed to work in the past. Digging a little deeper reveals a commit on 26. August 2019 that fixed an items-only updating bug and was released as part of version 3.0.0. Since the last-known-working version of POD Baugarantie apparently used an older version than that, we tentatively concluded that it worked by lucky coincidence in the past (items-only updating from React side would've yielded wrong UX but was  masked since the component did not properly respond to said updating because of the bug).

Closing the bug at this level of research.

**Closed as completed by markus-walther** 2020-01-07 12:27 UTC
Labels: Bug, High-prio
