### ISSUE TITLE
IE 11 polyfills are not working

### ISSUE THREAD

**Issue by jackblackCH** [axa-ch/patterns-library#783] opened 2019-01-16 14:30 UTC
Reproduce -> Open i.,e tab component on i.e Windows 10 in IE11.

**Comment by AndyOGo** [comment] 2019-01-16 14:50
@jackblackCH 
May I asked you specify which polyfills you mean?

In case you are talking about the custom-element polyfills, I highly doubt that they are the cause of the bug, all test cases are provided online by WebReflection and can be run by yourself:
- see for [`document-register-element`](https://github.com/WebReflection/document-register-element#tested-on) [live test page](http://webreflection.github.io/document-register-element/test/) and [the test file](https://github.com/WebReflection/document-register-element/blob/master/test/document-register-element.js)
- see for [`custom-elements-builtin`](https://github.com/ungap/custom-elements-builtin#custom-elements-with-builtin-extends) [live test page ES5](https://ungap.github.io/custom-elements-builtin/test/es5/) and [live test page ES6-only](https://ungap.github.io/custom-elements-builtin/test/)

I rather think that we have a bug at our side.

**Comment by LucaMele** [comment] 2019-05-13 07:53
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Closed by LucaMele** 2019-05-13 07:53 UTC
Labels: bug
