### ISSUE TITLE
@axa-ch/toggle-switch can not be used as a controlled component

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1962] opened 2020-09-09 15:11 UTC
Version: "@axa-ch/toggle-switch": "^1.0.6"

## Expected Behavior

We should be able to use toggle switch as a controlled component and control active prop from the external state.

## Current Behavior

Toggle switch component respects only the initial active prop.

## Steps to Reproduce

Reproduction link: https://codesandbox.io/s/musing-leaf-c319r?file=/src/App.js

## Context (Environment)
KMU-20 state of related modules is not reflected correctly in the UI. If you toggle one module it can make changes to the other modules but these changes are not propagated in the UI toggle switches.

**Comment by danyball** [comment] 2020-09-11 06:23
We will check that. Thanks for reporting.

**Comment by danyball** [comment] 2020-09-11 07:39
@salle18 Try to reproduce the issue. Do you mean that the button at my sandbox should work? https://codesandbox.io/s/beautiful-pine-krglx?file=/src/App.js

**Comment by salle18** [comment] 2020-09-11 08:23
Yes, external change button should work.

Moreover toggle switch shouldn't be able to change state if we keep hardcoded value in the active prop.
If we set active={true} or active={false} toggle switch shouldn't be toggleable at all!


Small error in you sandbox, change onClick handler to take a function
`onClick={() => (tester = false)}` instead of onClick={(tester = false)}

**Comment by markus-walther** [comment] 2020-09-14 15:20
The request to support controlled-component mode under React does make sense.

However, this is **not a bug**, since it was nowhere promised that controlled-component mode would work (cf. the Readme).

This is a feature request and will be internally discussed by the team, with updates here.

**Closed as completed** 2020-09-28 15:29 UTC
Labels: Feature-request, Accepted
