### ISSUE TITLE
Datepicker: Days are not aligned correctly

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1804] opened 2020-06-05 14:55 UTC
I just installed version 7.0.8 and the days are left aligned instead of being centered.
<img width="545" alt="Bildschirmfoto 2020-06-05 um 16 46 46" src="https://user-images.githubusercontent.com/617005/83891373-56df0c00-a74d-11ea-80b1-ca0922d9e79a.png">

**Comment by danyball** [comment] 2020-06-08 05:50
At which environment do you have this effect? Can you reproduce that at patterns.axa.ch?

**Comment by campsafari** [comment] 2020-06-08 07:52
I just installed 7.0.8. and used it in React, setup was done according to the guide from the patterns library. Environment is Chrome 83.0.4103.97 on OS X

Ahh, I just saw that the auto margin of the buttons was overwritten by the UI Renderer CSS.  
`.o-aletheia__application__root input,
.o-aletheia__application__root button,
.o-aletheia__application__root select,
.o-aletheia__application__root optgroup,
.o-aletheia__application__root textarea {
    margin: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}`


Maybe  m-datepicker__calendar-cell  should be scoped under m-datepicker?

**Comment by danyball** [comment] 2020-06-11 06:05
Scoping CSS is not that easy. Is it possible that you do not overwrite that html tag and just set a css class to the elements you want to change?

How urgent is that for you? Because we will release the new versioning feature of our component architecture soon. And that issue is possibly fixed by that.

**Comment by campsafari** [comment] 2020-06-11 09:33
why not just do: 
```
.m-datepicker {
  position: relative;
  display: inline;

  &,
  & &__calendar-cell {
    @include typo(primary, medium);
  }
}
```

instead of the current implementation:
```
.m-datepicker {
  position: relative;
  display: inline;

  &,
  &__calendar-cell {
    @include typo(primary, medium);
  }
}
```

**Comment by LucaMele** [comment] 2020-06-11 10:06
@campsafari because it will increase unnecessary CSS specificity for more than 8 applications and it wont really fix the problem cause if you add another wrapping class we are again at the same point. I highly suggest to NOT style directly HTML Tags (in your example as i can understand is `button`) as it is very risky, especially as in your case you style ALL Buttons inside a class and all of its children. Super Risky thing to do and i highly suggest to fix this implementation in your POD.

Here a checklist for POD DEVs: https://github.com/axa-ch/create-pod-app#css -> `BEM naming with the pods name prefixed in front of the block name like: o-mycomponent-block__element--modifier` & `Do not override patterns library classes`

**Comment by LucaMele** [comment] 2020-06-11 10:08
Might help understanding why styling directly tag names is not a good idea: https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

**Comment by LucaMele** [comment] 2020-06-11 10:13
For the specificity: 

Specificity is a nightmare and you should keep specificity as low as possible all of the time. We already know that we do not use IDs in CSS but a chain of selectors are often just as bad (though not quite).

A selector like `.widget > h2 {}` has a higher specificity (as well as the other problems we discussed) than a selector like `.widget-title {}`.

`.nav li a {}` has a higher specificity than `.nav a` (and is also less efficient). Reducing selector length reduces selector specificity and that is very important. High specificity leads to self-induced specificity battles that can only be won by making subsequent selectors more specific (or using `!important`, 😱). This is a terrible thing. The easiest way to reduce specificity (after dropping IDs from your CSS completely) is to keep your selectors short.

**Comment by LucaMele** [comment] 2020-06-11 10:14
@campsafari because of these opinions and best practices we embrace, i will close the Issue. Feel free to text me on slack or make a call if you disagree with our decision. Thank you for reporting

**Closed as completed by LucaMele** 2020-06-11 10:14 UTC
Labels: Help wanted

**Comment by campsafari** [comment] 2020-06-11 10:49
yes I get your point. but I think the datepicker classes should be kept under the axa-datepicker scope.

**Comment by LucaMele** [comment] 2020-06-11 10:56
Thank you very much for sharing your opinion. We always gain a lot of value from someone else's option and ideas, thank you. In this case thought, we prefer sticking to BEM best practices. Thank you for your understanding
