### ISSUE TITLE
Can't use years-range in react

### ISSUE THREAD

**Issue by NoahLiechti** [axa-ch/patterns-library#1135] opened 2019-07-04 07:50 UTC
When using a years-range in allowedyears with react, the years show up in one item of the dropdown instead of displaying each year in one item.
**Code**
`allowedyears={['2019-2025', 2030, 2031]}`
**Result**
<img width="316" alt="Bildschirmfoto 2019-07-04 um 09 41 05" src="https://user-images.githubusercontent.com/38284563/60648735-d202b880-9e40-11e9-937d-70d2af956444.png">

**Comment by markus-walther** [comment] 2019-07-08 09:39
The issue is *not* specific to React, but rather pertains to *property* updates of `allowedyears` in general, of which React is but one case.

But: good find, thanks!

**Comment by markus-walther** [comment] 2019-07-08 16:27
Fixed in minor release 2.1.0.

**Closed by markus-walther** 2019-07-08 16:27 UTC
Labels: PROD_ISSUE, bug, high-prio
