### ISSUE TITLE
Hierachical Webcomponents Lifecycle order is not deterministic

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#42] opened 2017-12-06 13:11 UTC
**Edit:**
~~Markup should determine hierarchical components bootstrap order, but it **doesn't**!~~~
The spec allows to bootstrap components as they are defined, independent of the markup's structure. Though in the following case I need this order to be deterministic in sense of markup structure, not definition order.
 
Given following example I expect:

```html
<axa-parent>
  <axa-child></axa-child>
</axa-parent>
```

**Expected:**
```js
Parent -> constructor
Parent > connectedCallback
Child -> constructor
Child > connectedCallback
```

Instead the definition of a web-component dictates the order of it's bootstrapping process.
**Observed:**
```js
index.js:579 Child -> constructor
index.js:588 Child > connectedCallback
index.js:542 Parent -> constructor
index.js:551 Parent > connectedCallback
```

<img width="1440" alt="screen shot 2017-12-06 at 14 06 04" src="https://user-images.githubusercontent.com/914443/33663216-5c8a5e62-da8f-11e7-9cfc-e80b7864cc6f.png">

**Comment by LucaMele** [comment] 2017-12-06 13:27
Behaviour respect the specs, therefore no bug.

...Because element definition can occur at any time, a non-custom element could be created, and then later become a custom element after an appropriate definition is registered. We call this process "upgrading" the element, from a normal element into a custom element.

Upgrades enable scenarios where it may be preferable for custom element definitions to be registered after relevant elements have been initially created, such as by the parser. They allow progressive enhancement of the content in the custom element....

**Comment by LucaMele** [comment] 2017-12-06 13:27
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements

**Comment by LucaMele** [comment] 2017-12-06 13:29
Personal Preferred features for standard documents are not a criteria for bug reports.

**Comment by LucaMele** [comment] 2017-12-06 13:30
https://html.spec.whatwg.org/multipage/custom-elements.html#element-definition

**Comment by LucaMele** [comment] 2017-12-06 13:31
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-definition

**Comment by AndyOGo** [comment] 2017-12-06 13:31
It's a bug in the sense of being not deterministic, which makes it complex and not simple.
Further more, somehow a child component should be able to know what happens around of it.

**Comment by LucaMele** [comment] 2017-12-06 13:48
Maybe for the w3c but here is not as behaviour follows the spec. Lets open a new issue for finding a solution for the problem together. As it is not a bug, i close it again

**Comment by AndyOGo** [comment] 2017-12-06 13:55
I admit, it does what it says in the spec.
Personally I consider both valid. So I turn it into an enhancement.

**Closed** 2017-12-07 12:18 UTC
Labels: enhancement
