### ISSUE TITLE
Datepicker year in dropdown is not completely displayed (Safari Desktop)

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#2176] opened 2021-06-03 12:09 UTC
Description:
The latest datepicker doesnt completely displays the year in the dropdown. This only happens in Safari Desktop Browser.

## Expected Behavior
The year should be fully displayed in the dropdown.

## Current Behavior
Instead only the first two numbers are displayed.

## Steps to Reproduce
1. go to our pod https://www.acc.axa.ch/de/rechner/haushaltversicherung.html#/start
2. go to "Birthday Screen" where u can see the datepicker.
3. u will see that year is not fully displayed.

![image](https://user-images.githubusercontent.com/57704956/120642405-1e176700-c475-11eb-8149-bb9a37729735.png)

thanks for your help.

best regards 

Quan

**Comment by 01231** [comment] 2021-06-07 06:20
Thanks for reporting. We'll have a look 👍🏼

**Comment by raphaellueckl** [comment] 2021-06-10 14:01
Hi @chiquan-hong 

Can it be that you are using an outdated version? Because here, we cannot reproduce that issue:

https://patterns.axa.ch/?path=/story/components-datepicker--datepicker

**Comment by chiquan-hong** [comment] 2021-06-10 14:28
> Hi @chiquan-hong
> 
> Can it be that you are using an outdated version? Because here, we cannot reproduce that issue:
> 
> https://patterns.axa.ch/?path=/story/components-datepicker--datepicker

no we have Version 15.0.5 at that time. I couldnt reproduce it in Browserstack ether. May @marek-polak, can u try it again, cause Marek could reproduce it at that time on his macbook.

**Comment by marek-polak** [comment] 2021-06-14 11:44
Issue is not reproducible neither in Storybook: ![image](https://user-images.githubusercontent.com/73373/121886087-a91e1a00-cd1d-11eb-8d57-01f20fdb16f7.png), nor in the DHH Pod (ACC).
It seems that the version upgrade did solve it.

**Comment by 01231** [comment] 2021-06-15 06:36
I'm closing this one because it seems to be solved. If it is still an issue please reopen.

**Closed as completed by 01231** 2021-06-15 06:36 UTC
Labels: Bug
