### ISSUE TITLE
[File-Upload] allowedFileTypes doesn't work on windows

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#2225] opened 2021-09-23 07:58 UTC
Found for CSV files, but on a first glance, it looks like the filter does not work at all.

HINT: Maybe also check on a non-axa windows laptop, just to be sure.

![Annotation 2021-09-23 094502](https://user-images.githubusercontent.com/8248662/134472691-791880c0-f7a7-4c7e-9ab2-f36d419fc21c.png)

**Comment by markus-walther** [comment] 2021-10-26 16:09
The claimed generality of the bug on Windows is not true: e.g. a PNG image can be dragged onto https://patterns.axa.ch/?path=/story/components-file-upload--file-upload without problems.

As for the specific claim for CSV files:

- https://stackoverflow.com/questions/7076042/what-mime-type-should-i-use-for-csv does mention the recommended MIME type of _text/csv_
- when debugging with an Excel-generated CSV file under Windows 10 Enterprise/Google Chrome 95, we see that the **actual MIME type** differs under Windows:
![file-upload-CSV](https://user-images.githubusercontent.com/46926507/138916226-b61bb699-846f-4dfd-86de-f6e5c71bd699.PNG)

This is mentioned in the referenced StackOverflow article.
- adding _both_ text/csv and **application/vnd.ms-excel** to _allowedFileTypes_ makes the 'bug' go away:
![file-upload-CSV-1](https://user-images.githubusercontent.com/46926507/138916262-f441c14d-227d-433f-985d-c0e647dc8c54.PNG)

**Conclusion:** This is **not a bug.** It is an oddity/non-standard-conformance issue of MS Windows that can be easily fixed by the app developer _using_ &lt;axa-file-upload&gt;, namely by adding 2 appropriate MIME types.

**Closed as completed** 2021-10-26 16:12 UTC
Labels: Bug
