### ISSUE TITLE
Test "Button Link" not always running on Travis

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1611] opened 2020-01-14 12:25 UTC
Sometimes this test fails:

```
 Button Link - basic functionality
 ✖ should render button-link
   1) AssertionError: expected false to be truthy
      Browser: HeadlessChrome 62.0.3202 / Linux 0.0.0
          6 |  `${host}/iframe.html?id=atoms-button-link--button-link`
          7 |);
          8 |
          9 |test('should render button-link', async t => {
         10 |  const $axaButton = await Selector('axa-button-link');
       > 11 |  await t.expect($axaButton.exists).ok();
         12 |  const $axaButtonShadow = await Selector(
         13 |    () =>
      document.querySelector('axa-button-link').shadowRoot
         14 |  );
         15 |  const $axaButtonShadowEl = await
      $axaButtonShadow.find('.a-button-link');
         16 |  await t.expect($axaButtonShadowEl.exists).ok();
         at ok
      (/home/travis/build/axa-ch/patterns-library/src/components/10-atoms/button-link/ui.test.js:11:37)
```

**Comment by danyball** [comment] 2020-01-22 07:16
Nachdem ich eine MD Datei geändert hatte....??

```
Button Link - basic functionality
 ✓ should render button-link
 ✖ should style button-link default css (test axa blue bg color)
   1) An error occurred in Selector code:
      TypeError: Cannot read property 'shadowRoot' of null
```

**Comment by raphaellueckl** [comment] 2020-01-24 16:39
@danyball I cannot reproduce this locally. The test also run fast, so not even remotely any sign of a sloppy test (the test only checks if it's there). I guess this is about travis free-tier is probably too slow and the webcomponents takes too long to load.

Maybe this could be solved by not running 4 threads concurrently, but that would imho be a very bad fix. The fix I would suggest is shutting down travis. It's redundant to the azure pipeline - just way slower - and I didn't use it in a long time.

Should we close this issue?

**Comment by danyball** [comment] 2020-01-31 12:51
Jep, i think thats a problem on travis. Ok, let shut it down. but: is there another way to see the debug infos on our macs?

**Comment by danyball** [comment] 2020-03-04 12:55
Same test fails with different error on Azure #1677

**Comment by raphaellueckl** [comment] 2020-07-03 12:20
@danyball can we close this issue? I guess we will not go back to travis and rather use github action, if anything. and i am unaware that this would frequently happen on azure, but did not validate my thesis.

**Closed as completed** 2020-07-03 15:03 UTC
Labels: Bug
