### ISSUE TITLE
New compoment: Loading indicator

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#655] opened 2018-11-05 13:35 UTC
We need a compoment, that would indicate that content is still loading.

Use cases:
- noscript (html+css) untill the JS APP bootstraps
- without children, to be displayed above/under/instead the content
- with children: children are non-clickable and greyed-out during "isLoading"

Example: blue square - a squashing animation

![image](https://user-images.githubusercontent.com/43809369/48001036-ac81ab80-e107-11e8-8129-9fd8c626ff9a.png)

**Comment by AndyOGo** [comment] 2018-11-05 13:37
duplicate of #461 

@MarekLacoAXA 
May I ask you to enhance the original issue, if you miss some thing?

**Closed by AndyOGo** 2018-11-05 13:37 UTC
Labels: enhancement
