### ISSUE TITLE
custom-elements break jest

### ISSUE THREAD

**Issue by jan-capiak** [axa-ch/patterns-library#786] opened 2019-01-17 09:31 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Problem
Testing custom elements (patterns-library components) with jest throws an error.
The problem is that jsdom doesnt support custom elements.
Github issue on jsdom: https://github.com/jsdom/jsdom/issues/1030

What is then the way to test your application with patterns-library components?
Thanks

**Comment by AndyOGo** [comment] 2019-01-17 09:35
@jan-capiak 
Thanks for your issue.
That's correct custom-elements aren't supported by jsdom so far.

But we use custom-element polyfills, which should work for jsdom too.
Though we have to test this, because I tried it.

**Comment by AndyOGo** [comment] 2019-01-17 09:41
Same issue for aletheia

**Comment by LucaMele** [comment] 2019-01-17 09:44
@jan-capiak yes if u add polyfills it should work

**Comment by AndyOGo** [comment] 2019-01-17 10:19
@jan-capiak 
@LucaMele 
@MKaHead 
Please read my update above regarding Jest and Enzyme:

> Next you may face issues with **snapshot-testing** done by **Jest** or **Enzym**.
Because they deal with **virtual DOM**, and custom elements are DOM not V-DOM.
Furthermore Jest and Enzym implement their own V-DOM render functionality to support shallow snapshots 💣 

> So in a worst case scenario we have to rewrite `withReact` to `null` if it is used within a test environment 🚀

**Comment by AndyOGo** [comment] 2019-01-17 11:35
@jan-capiak 
@LucaMele 
We should have reproduction repo

**Comment by jan-capiak** [comment] 2019-01-17 14:03
Thank you @AndyOGo  for help 👍 
Importing this `import 'document-register-element';` in jest config solved the issue with customElements is undefined.

Another issue is with `withReact` .
When i import patterns-library component without `withReact` and then test that component, it works, but not with `withReact`.

Can there be some fix/workaround in patterns-library `withReact` for that?

**Comment by AndyOGo** [comment] 2019-01-17 14:36
@jan-capiak 
Thank you for your feedback.

It would very awesome if we could see the whole code causing your issue.
May I asked you to share a reproduction repo?

**Comment by AndyOGo** [comment] 2019-01-24 10:16
Thanks @MKaHead 

@LucaMele 
@jan-capiak 
Yes indeed, we face maybe a bigger problem here.
Because we not only one functionality which needs to deal with cross-browser issues.

And please be aware that `jsdom` only implements a subset of the DOM API

**Comment by LucaMele** [comment] 2019-05-13 07:53
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Closed by LucaMele** 2019-05-13 07:53 UTC
Labels: PROD_ISSUE, bug, high-prio
