### ISSUE TITLE
Please support blue-ocean variant

### ISSUE THREAD

**Issue by urswiss** [axa-ch/patterns-library#2029] opened 2020-11-10 09:21 UTC
Add blue-ocean variant

## Expected Behavior
'button' and 'button-link' should accept `variant="blue-ocean"` without a linter error.

## Current Behavior
Currently, there is a linting error when using the blue-ocean variant:
![image](https://user-images.githubusercontent.com/19600534/98654076-20ca3780-233e-11eb-8ba7-128a72b7e792.png)

**Comment by raphaellueckl** [comment] 2020-11-10 10:46
This is not a bug, this is not something we support in the pattern library. I thought at first that we forgot to add the typescript-type. Therefore I close this issue. If this is a feature request, contact our designers, as they would have to approve this.

**Closed as completed by raphaellueckl** 2020-11-10 10:46 UTC
Labels: Bug

**Comment by urswiss** [comment] 2020-11-10 10:57
I just removed the code line `variant="blue-ocean"` and now the linter error also disappeared 👍 
As `blue-ocean` is the default there is no need to pass this explicitly
