### ISSUE TITLE
Datepicker throws an Error in IE with React

### ISSUE THREAD

**Issue by ranostaj** [axa-ch/patterns-library#761] opened 2018-12-17 11:27 UTC
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Steps to reproduce
TODO::

## Expected Behavior

Using date picker with React and Date picker should render.

Implementation:

```
<AXADatepicker onAxaChange={this.handleDatepickerChangeTo} />
``` 

## Actual Behavior

Throws an IE error

![image](https://user-images.githubusercontent.com/61942/50084278-b6aec380-01f6-11e9-815c-5d1fa27d6fd7.png)

![image](https://user-images.githubusercontent.com/61942/50084387-20c76880-01f7-11e9-876e-5b97b352d52f.png)

## Specifications

 - Browser: IE 11
 - Browser Version: IE 11
 - Patterns library Version: 2.0.1-beta.242

**Comment by AndyOGo** [comment] 2018-12-17 11:42
@ranostaj 
Very likely that it's an `constructor` caveat issue.
More info in our docs and linked readmes:
https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTING.md#constructor

**Comment by LucaMele** [comment] 2018-12-17 13:31
@ranostaj yes i had that issue as well. Make sure you are using the latest version of the patterns-library and that you include all the polyfills as is done here:

`https://github.com/axa-ch/patterns-library/blob/develop/src/index.js` and `https://github.com/axa-ch/patterns-library/blob/develop/src/js/es6-polyfills.js`

**Comment by LucaMele** [comment] 2018-12-17 13:36
If issue is not resolved with what i just said, means that we still have somewhere a constructor caveat issue as specified from andy.

If is urgent and you are not using built-ins like `<td is="axa-td">` you can use this polyfill: `npm install @webcomponents/webcomponentsjs`. Make sure you are only importing Custom element polyfill: `import '@webcomponents/webcomponentsjs/bundles/webcomponents-ce';`

**Comment by LucaMele** [comment] 2018-12-17 13:38
If you decide to use the wecomponent polyfill, make sure you watch this issue and remove it when this is fixed in order to be compliant with future developments of the patterns-library

**Comment by ranostaj** [comment] 2018-12-17 14:38
I'm importing, but the issues still persists and using the latest version
```
import 'babel-polyfill';
import '@webcomponents/custom-elements';
```
@AndyOGo Not sure how is this related to the contructor issue I'm using Date picker inside React Component which is Class but it is not using Contructor method

**Comment by AndyOGo** [comment] 2018-12-17 14:42
@ranostaj 
The issue is in the code of datepicker.
It isn't correctly developed to support the asynchronous nature of custom elements and the difference of an instance being live in the visible DOM and non-live just in memory...

**First issue:** never do DOM inteaction winthin `init()`:
https://github.com/axa-ch/patterns-library/blob/a76972aff9e102fa983bdbfcb631c84d92f8a4e1/src/components/o-datepicker/index.js#L26-L35

**Second issue:** always check if properties exist, before trying to access them:
https://github.com/axa-ch/patterns-library/blob/a76972aff9e102fa983bdbfcb631c84d92f8a4e1/src/components/o-datepicker/index.js#L51-L55

**Comment by LucaMele** [comment] 2018-12-17 14:45
there is a branch that should fix the wrong init implementation: https://github.com/axa-ch/patterns-library/tree/feature/datepicker-fixes

**Comment by AndyOGo** [comment] 2018-12-17 14:47
@LucaMele 
Great. Though it's not only init that is wrong...

**Comment by LucaMele** [comment] 2018-12-17 14:49
@AndyOGo i believe in more than one component we do DOM selections. I dont think thought the init issue here would fix the Issue as the only thing the datepicker init does is to listen to events and select classes. That error message @ranostaj is weird. How can the Intl API not support `en-uk`? What browser and what language do you have?

**Comment by LucaMele** [comment] 2018-12-17 14:58
@ranostaj polyfill is imported in this way: `import '@webcomponents/webcomponentsjs/bundles/webcomponents-ce';`

**Comment by AndyOGo** [comment] 2018-12-17 14:58
@LucaMele 
Okay, I don't know about all other components.

Let's look at this one. This has at least two bugs, as I pointed out above:

1. DOM operations in constructor/init
2. not checking if `this.datepicker` property exists
3. maybe more

> I dont think the init issue is responsible for the Issue in this BUG as the only thing the datepicker init does is to listen to events and select DOM Nodes.

The bug I spotted is not about the internal stuff of the Datepicker.
It's about how the custom element of the Datepicker is made ready, connected, live or however you want to name it.

**Comment by LucaMele** [comment] 2018-12-17 15:00
ok but still regarding point 1, no DOM manipulations are performed. Only DOM SELECTIONS. And the spec that you linked CLEARLY says: "The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods"

**Comment by LucaMele** [comment] 2018-12-17 15:00
Selecting and add event listeners does not "gain any attributes or children..."

**Comment by LucaMele** [comment] 2018-12-17 15:01
and: "In general, the constructor should be used to set up initial state and default values, and to set up event listeners and possibly a shadow root."

**Comment by LucaMele** [comment] 2018-12-17 15:02
therefore i disagree on issue 1 you pointed out and strongly belive it has nothing to do with @ranostaj issue.

**Comment by LucaMele** [comment] 2018-12-17 15:03
@AndyOGo some are on root some not and this i known and is a BUG yes. But not relevant to the issue @ranostaj has IMHO

**Comment by AndyOGo** [comment] 2018-12-17 15:06
Okay, then I'm afraid I can't help you.

**Comment by LucaMele** [comment] 2018-12-17 15:07
ok :( enjoy Holidays @AndyOGo i need you back relaxed and great as usual!

**Comment by AndyOGo** [comment] 2018-12-17 15:09
Thanks @LucaMele 
Just keep one more thing in mind, `connectCallback` and `disconnectedCallback` can be called more than once. Just a guess.

**Comment by LucaMele** [comment] 2018-12-17 15:10
@AndyOGo yepp i know i will debug and see as soon as @ranostaj gives me more details about his error. You relax and take holidays as holiday :)

**Comment by ranostaj** [comment] 2018-12-17 15:15
Thank you guys, I added `import '@webcomponents/webcomponentsjs/bundles/webcomponents-ce';` but no luck with that one. Getting the same error, also I have tried to pass locale as props but it is not passing into DatePicker :(

**Comment by LucaMele** [comment] 2018-12-17 15:34
ok @ranostaj. We need to analyse it futher. i might have time tomorrow. @NoahLiechti or @jackblackCH does one of you have time here?

**Comment by ranostaj** [comment] 2018-12-20 08:20
Hey @LucaMele , any update on this one? Thanks

**Comment by ranostaj** [comment] 2018-12-20 08:37
@LucaMele Thank's for the update, it is not blocking us right now, but beginning next year we need to have it fixed for the client demo. I'll try the locale props and let you know

**Comment by NoahLiechti** [comment] 2018-12-20 10:22
@ranostaj @LucaMele the problem is, that when no locale is passed the default is set to "en-uk" wich is false. It should be "en-UK". So to prevent the error set the locale as Luca described. 
In the branch https://github.com/axa-ch/patterns-library/tree/feature/datepicker-fixes this error is fixed.

**Comment by ranostaj** [comment] 2018-12-20 14:57
@NoahLiechti even "en-UK" is throwing the same error

**Comment by NoahLiechti** [comment] 2018-12-21 08:04
@ranostaj that's suspicious. In my case it works with "en-uk", "en-UK" and "". I can promise, that this bug will be fixed when the branch datepicker-fixes gets merged.

**Comment by LucaMele** [comment] 2019-05-13 07:53
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Closed by LucaMele** 2019-05-13 07:53 UTC
Labels: PROD_ISSUE, bug, high-prio
