### ISSUE TITLE
axa-file-upload: 1 end-to-end test fails

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/patterns-library#1335] opened 2019-09-16 13:25 UTC
The end-to-end test in ui.test.js fails in line 188 under Travis (see screenshot).
An attempt to add 50 ms waiting time after line 180 did not fix the problem.

Please investigate and fix this.

![Screen Shot 2019-09-16 at 15 21 17](https://user-images.githubusercontent.com/46926507/64961451-d5311080-d895-11e9-97f3-c96b7b545de8.png)

**Comment by raphaellueckl** [comment] 2019-10-16 16:02
@NoahLiechti This is fixed now by outcommenting, right?

**Comment by 01231** [comment] 2019-10-17 06:09
@raphaellueckl yes it is

**Comment by danyball** [comment] 2019-11-01 15:10
I just had another failed UI Test @NoahLiechti .
https://travis-ci.org/axa-ch/patterns-library/jobs/606033468?utm_medium=notification&utm_source=github_status

The other test was running??
![image](https://user-images.githubusercontent.com/7448004/68034546-21a7a280-fcc2-11e9-8eed-e8bd2b7c6e1a.png)


```

File upload
 ✓ should render file-upload
 ✖ should upload file and switch view
   1) AssertionError: expected false to be truthy
      Browser: HeadlessChrome 62.0.3202 / Linux 0.0.0
         39 |  const $fileOverviewElem = await Selector(() =>
         40 |    document
         41 |      .querySelector('axa-file-upload')
         42 |
      .shadowRoot.querySelector('.js-file-upload__dropzone-file-overview')
         43 |  );
       > 44 |  await t.expect($fileOverviewElem.exists).ok();
         45 |});
         46 |
         47 |test("shouldn't upload file because it's an invalid type",
      async t => {
         48 |  const $inputFileInputElem = await Selector(() =>
         49 |    document
         at ok
      (/home/travis/build/axa-ch/patterns-library/src/components/20-molecules/file-upload/ui.test.js:44:44)
```

**Comment by danyball** [comment] 2019-11-14 07:32
I think the problem is the `setFilesToUpload()` function.

**Comment by danyball** [comment] 2019-11-15 16:05
Just for documentation: t.wait(1) wont work, but to evaluate the DOM element of `Selector` works. `.count` got the right value after that?!

**Closed** 2019-11-21 12:50 UTC
Labels: bug
